  nginx:
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    env_file: .env
    networks:
      - inception
    restart: always